# **MATRIC OPERATION**

In [ ]:
import numpy as np
mat1=np.array(([1,2,3],[4,5,6],[7,8,9]))
mat2=np.array(([9,8,7],[6,5,4],[3,2,1]))
print("mat1 =\n",mat1)
print("\n")
print("mat2 =\n",mat2)
print("\n")
print("mat1+mat2 =\n",mat1+mat2)
print("\n")
print("mat2-mat1 =\n",mat2-mat1)
print("\n")
print("mat1*mat2 =\n",mat1*mat2)
print("\n")
print("mat1/mat2 =\n",mat1/mat2)
print("\n")
print("square root of mat1 =\n",np.sqrt(mat1))

mat1 =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


mat2 =
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


mat1+mat2 =
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


mat2-mat1 =
 [[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]


mat1*mat2 =
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


mat1/mat2 =
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


square root of mat1 =
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
# Python program for matrix operations

# importing numpy
import numpy as np

mat1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# adding matrices
print("mat1+mat2")
print(mat1+mat2)
print(np.add(mat1,mat2))
print(np.add(mat1,mat2))
print() # prints newline

# subtracting matrices
print("mat1-mat2...")
print(mat1-mat2)

print("np.subtract(mat1,mat2)...")
print(np.subtract(mat1,mat2))
print() # prints newline

# dividing matrices
print("mat1/mat2...")
print(mat1/mat2)
print("np.divide(mat1,mat2)...")
print(np.divide(mat1,mat2))
print() # prints newline

# multiplying matrices
print("mat1*mat2...")
print(mat1*mat2)
print("np.multiply(mat1,mat2)...")
print(np.multiply(mat1,mat2))
print() # prints newline

# producting matrices
print("np.dot(mat1,mat2)...")
print(np.dot(mat1,mat2))
print() # prints newline

# Square root of matrix elements
print("np.sqrt(mat1)...")
print(np.sqrt(mat1))
print() # prints newline

# Square root of matrix elements
print("np.sqrt(mat2)...")
print(np.sqrt(mat2))
print() # prints newline

mat1+mat2
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]

mat1-mat2...
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]
np.subtract(mat1,mat2)...
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]

mat1/mat2...
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
np.divide(mat1,mat2)...
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]

mat1*mat2...
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
np.multiply(mat1,mat2)...
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]

np.dot(mat1,mat2)...
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]

np.sqrt(mat1)...
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]
 [8.36660027 8.94427191 9.48683298]]

np.sqrt(mat2)...
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]



# **PROBABILITY**

In [ ]:
import pandas as pd
import numpy as np

#create pandas DataFrame with raw data
df = pd.DataFrame({'gender': np.repeat(np.array(['Male', 'Female']), 150),'sport': np.repeat(np.array(['Baseball', 'Basketball', 'Football','Soccer', 'Baseball', 'Basketball',
'Football', 'Soccer']),
(34, 40, 58, 18, 34, 52, 20, 44))})

#produce contingency table to summarize raw data
survey_data = pd.crosstab(index=df['gender'], columns=df['sport'], margins=True)

#view contingency table
print("surver data ")
print(survey_data)

#extract value in second row and first column
print("\nextract value in second row and first column = ")
print(survey_data.iloc[1, 0])

#calculate probability of being male, given that individual prefers baseball
print("\ncalculate probability of being male, given that individual prefers baseball = ")
print(survey_data.iloc[1, 0] / survey_data.iloc[2, 0])

#calculate probability of preferring basketball, given that individual is female
print("\ncalculate probability of preferring basketball, given that individual is female = ")
print(survey_data.iloc[0, 1] / survey_data.iloc[0, 4])


surver data 
sport   Baseball  Basketball  Football  Soccer  All
gender                                             
Female        34          52        20      44  150
Male          34          40        58      18  150
All           68          92        78      62  300

extract value in second row and first column = 
34

calculate probability of being male, given that individual prefers baseball = 
0.5

calculate probability of preferring basketball, given that individual is female = 
0.3466666666666667


# **Confusion matrix**
**Splitting the dataset , Feature Scaling , Naive Bayes model**

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('/content/Social _Network_Ads.csv - Sheet1.csv')
X = dataset.iloc[:, [3, 4]].values
y = dataset.iloc[:, -1].values

FileNotFoundError: ignored

In [ ]:
X

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


In [ ]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)

In [ ]:
ac

In [ ]:
cm

# **singular value decomposition**

In [ ]:
# singular value decomposition
import numpy as np
import pandas as pd

In [ ]:
from numpy import array
from scipy.linalg import svd

In [ ]:
#defining a  matrix
a=array([[7,8,9],[1,2,3],[4,5,6]])
print(a)

[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [ ]:
u1,s1,v1 =svd(a)

In [ ]:
print(u1)

[[-0.82633754  0.38794278 -0.40824829]
 [-0.21483724 -0.88723069 -0.40824829]
 [-0.52058739 -0.24964395  0.81649658]]


In [ ]:
print(s1)

[1.68481034e+01 1.06836951e+00 5.89123300e-16]


In [ ]:
print(v1)

[[-0.47967118 -0.57236779 -0.66506441]
 [ 0.77669099  0.07568647 -0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [ ]:
#reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

In [ ]:
#defining matrix
b=array([[1,2,3],[4,5,6],[7,8,9]])#
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#factorization
u2,s2,v2=svd(b)

In [ ]:
print("u = ")
print(u2)

u = 
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]


In [ ]:
print("s = ")
print(s2)

s = 
[1.68481034e+01 1.06836951e+00 4.41842475e-16]


In [ ]:
print("v = ")
print(v2)

v = 
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [ ]:
#create a m*n sigma matrix
sigma=zeros((b.shape[0],b.shape[1]))
print(sigma)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#populate sigma with n*n diagonal
sigma[:b.shape[1], :b.shape[1]]=diag(s)
print(diag(s))

NameError: ignored

In [ ]:
#reconstruct matrix
c=u2.dot(sigma.dot(v2))
print(c)

# **truth_table_generator**

In [ ]:
pip install truth_table_generator

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for truth_table_generator: filename=truth_table_generator-1.1.2-py3-none-any.whl size=13955 sha256=4dcbc490cbc8693fb17971c55d08b2a622130c9340a59997dc45637fe253d655
  Stored in directory: /root/.cache/pip/wheels/4f/2f/f9/488fa56346e1e8aed09c0e417480798766894e6c7c4f5d5425
  Created wheel for PTable: filename=PTable-0.9.2-py3-none-any.whl size=22922 sha256=cc20a7999666dd2645aece82cdc8d8f9ef3ecc2830d126ea229eb70cb46143fd
  Stored in directory: /root/.cache/pip/wheels/b8/d5/8b/e0c9765594e0dc8093aae5f67eacc08b9b533da598c710b54a
Successfully built truth_table_generator PTable


In [ ]:
import ttg
print(ttg.Truths(['p','q','r']))


+-----+-----+-----+
|  p  |  q  |  r  |
|-----+-----+-----|
|  1  |  1  |  1  |
|  1  |  1  |  0  |
|  1  |  0  |  1  |
|  1  |  0  |  0  |
|  0  |  1  |  1  |
|  0  |  1  |  0  |
|  0  |  0  |  1  |
|  0  |  0  |  0  |
+-----+-----+-----+


In [ ]:
print(ttg.Truths(['p','q','r'],['~p','~q','~r']))

+-----+-----+-----+------+------+------+
|  p  |  q  |  r  |  ~p  |  ~q  |  ~r  |
|-----+-----+-----+------+------+------|
|  1  |  1  |  1  |  0   |  0   |  0   |
|  1  |  1  |  0  |  0   |  0   |  1   |
|  1  |  0  |  1  |  0   |  1   |  0   |
|  1  |  0  |  0  |  0   |  1   |  1   |
|  0  |  1  |  1  |  1   |  0   |  0   |
|  0  |  1  |  0  |  1   |  0   |  1   |
|  0  |  0  |  1  |  1   |  1   |  0   |
|  0  |  0  |  0  |  1   |  1   |  1   |
+-----+-----+-----+------+------+------+


In [ ]:
print("pos = ")
print(ttg.Truths(['p','q','r'],['~p','~q','~r','p or q or r','p or ~q or r','~p or q or ~r','(p or q or r)and(p or ~q or r)and(~p or q or ~r))']))

pos = 
+-----+-----+-----+------+------+------+---------------+----------------+-----------------+-----------------------------------------------------+
|  p  |  q  |  r  |  ~p  |  ~q  |  ~r  |  p or q or r  |  p or ~q or r  |  ~p or q or ~r  |  (p or q or r)and(p or ~q or r)and(~p or q or ~r))  |
|-----+-----+-----+------+------+------+---------------+----------------+-----------------+-----------------------------------------------------|
|  1  |  1  |  1  |  0   |  0   |  0   |       1       |       1        |        1        |                          1                          |
|  1  |  1  |  0  |  0   |  0   |  1   |       1       |       1        |        1        |                          1                          |
|  1  |  0  |  1  |  0   |  1   |  0   |       1       |       1        |        0        |                          0                          |
|  1  |  0  |  0  |  0   |  1   |  1   |       1       |       1        |        1        |                          

In [ ]:
print("sop = ")
print(ttg.Truths(['p','q','r'],['p and q and r','p and ~q and r','~p and q and ~r','(p and q and r)or(p and ~q and r)or(~p and q and ~r))']))

sop = 
+-----+-----+-----+-----------------+------------------+-------------------+---------------------------------------------------------+
|  p  |  q  |  r  |  p and q and r  |  p and ~q and r  |  ~p and q and ~r  |  (p and q and r)or(p and ~q and r)or(~p and q and ~r))  |
|-----+-----+-----+-----------------+------------------+-------------------+---------------------------------------------------------|
|  1  |  1  |  1  |        1        |        0         |         0         |                            1                            |
|  1  |  1  |  0  |        0        |        0         |         0         |                            0                            |
|  1  |  0  |  1  |        0        |        1         |         0         |                            1                            |
|  1  |  0  |  0  |        0        |        0         |         0         |                            0                            |
|  0  |  1  |  1  |        0        |        0  

# **Hypothesis**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/find_S.csv")
print(data)

FileNotFoundError: ignored

In [ ]:
concept=np.array(data)[:,:-1]
print(concept)

In [ ]:
target=np.array(data)[:,-1]
print(target)

In [ ]:
''' DEFINING MODEL '''
def func(concept,target):
    for i , val in enumerate(target):
        if val=="Yes":
            specific_hypothesis=concept[i].copy()
            print(specific_hypothesis)
            break
    count=0
    for i, val in enumerate(concept):
        count=count+1
        print("concept=",concept[i])
        print("count=",count)
        if target[i]=="Yes":
            print("target[i]=",target[i])
            #print(len(specific_hypothesis))
            for x in range (len(specific_hypothesis)):
                print("x=",x)
                if val[x]!= specific_hypothesis[x]:
                    #print("val[x]=",val[x])
                    specific_hypothesis[x]='?'
                    print("specific_hypothesis[x]=",specific_hypothesis)
                else:
                    pass
    print(specific_hypothesis)


In [ ]:
#Calling Function func function
print("Final Specific Hypothesis = ",func(concept,target))