In [ ]:
# singular value decomposition 
import numpy as np
import pandas as pd

In [ ]:
from numpy import array
from scipy.linalg import svd

In [ ]:
#defining a  matrix
a=array([[7,8,9],[1,2,3],[4,5,6]])
print(a)

[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [ ]:
u1,s1,v1 =svd(a)

In [ ]:
print(u1)

[[-0.82633754  0.38794278 -0.40824829]
 [-0.21483724 -0.88723069 -0.40824829]
 [-0.52058739 -0.24964395  0.81649658]]


In [ ]:
print(s1)

[1.68481034e+01 1.06836951e+00 5.89123300e-16]


In [ ]:
print(v1)

[[-0.47967118 -0.57236779 -0.66506441]
 [ 0.77669099  0.07568647 -0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [ ]:
#reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

In [ ]:
#defining matrix
b=array([[1,2,3],[4,5,6],[7,8,9]])#
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#factorization  
u2,s2,v2=svd(b)

In [ ]:
print("u = ")
print(u2)

u = 
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]


In [ ]:
print("s = ")
print(s2)

s = 
[1.68481034e+01 1.06836951e+00 4.41842475e-16]


In [ ]:
print("v = ")
print(v2)

v = 
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [ ]:
#create a m*n sigma matrix
sigma=zeros((b.shape[0],b.shape[1]))
print(sigma)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#populate sigma with n*n diagonal
sigma[:b.shape[1], :b.shape[1]]=diag(s)
print(diag(s))

[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.41842475e-16]]


In [ ]:
#reconstruct matrix
c=u2.dot(sigma.dot(v2))
print(c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
